import Link from "next/link";
import { ArrowUpRight, CalendarDays, CircleAlert, CircleCheck, Users } from "lucide-react";
import { getTranslations } from "next-intl/server";
import type { DashboardRange } from "@/lib/services/dashboard-metrics-service";

type Metrics = Awaited<ReturnType<typeof import("@/lib/services/dashboard-metrics-service").getDashboardMetrics>>;

function money(value: number, locale: string, currency: string) { return new Intl.NumberFormat(locale, { style: "currency", currency, maximumFractionDigits: 0 }).format(value / 100); }

function RevenueChart({ series, locale, currency }: { series: Metrics["series"]; locale: string; currency: string }) {
  const max = Math.max(1, ...series.flatMap((day) => [day.planned, day.received]));
  const points = (key: "planned" | "received") => series.map((day, index) => `${series.length === 1 ? 50 : (index / (series.length - 1)) * 100},${92 - (day[key] / max) * 78}`).join(" ");
  return <div className="mt-6" aria-label="Evolução de receita"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-52 w-full overflow-visible"><path d="M0 92H100" className="stroke-border" strokeWidth=".7" /><polyline points={points("planned")} fill="none" className="stroke-muted-foreground/50" strokeWidth="1.3" strokeDasharray="3 3" vectorEffect="non-scaling-stroke" /><polyline points={points("received")} fill="none" className="stroke-primary" strokeWidth="2" vectorEffect="non-scaling-stroke" /></svg><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>{new Intl.DateTimeFormat(locale, { day: "numeric", month: "short" }).format(new Date(`${series[0]?.date}T12:00:00`))}</span><span>{money(max, locale, currency)}</span><span>{new Intl.DateTimeFormat(locale, { day: "numeric", month: "short" }).format(new Date(`${series.at(-1)?.date}T12:00:00`))}</span></div></div>;
}

export async function DashboardOverview({ metrics, role, locale, currency }: { metrics: Metrics; role: string; locale: string; currency: string }) {
  const t = await getTranslations("dashboard.overview"); const financial = role === "owner";
  const rangeOptions: DashboardRange[] = [1, 7, 30, 90];
  const stats = financial ? [
    { label: t("received"), value: money(metrics.receivedRevenue, locale, currency), hint: t("netOfRefunds") },
    { label: t("planned"), value: money(metrics.plannedRevenue, locale, currency), hint: t("validBookings") },
    { label: t("customers"), value: String(metrics.uniqueCustomers), hint: t("uniqueInPeriod") },
    { label: t("completed"), value: String(metrics.completedCount), hint: t("fromBookings", { count: metrics.bookingCount }) },
  ] : [
    { label: t("appointments"), value: String(metrics.bookingCount), hint: t("inPeriod") },
    { label: t("completed"), value: String(metrics.completedCount), hint: t("fromBookings", { count: metrics.bookingCount }) },
    { label: t("noShows"), value: `${Math.round(metrics.noShowRate * 100)}%`, hint: t("noShowCount", { count: metrics.noShowCount }) },
    { label: t("pendingPayments"), value: String(metrics.pendingPayments.length), hint: t("needAttention") },
  ];
  return <section className="space-y-8 p-5 md:p-8"><header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-medium text-primary">{role === "owner" ? t("businessPulse") : t("operationsPulse")}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{t("title")}</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">{t(role === "owner" ? "ownerDescription" : "managerDescription")}</p></div><div className="inline-flex w-fit rounded-lg border bg-card p-1">{rangeOptions.map((range) => <Link key={range} href={`/dashboard?range=${range}`} className={`rounded-md px-3 py-1.5 text-sm font-medium transition-colors ${metrics.range === range ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{range === 1 ? t("today") : t("days", { count: range })}</Link>)}</div></header>
    <div className="grid gap-px overflow-hidden rounded-xl border bg-border sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <article key={stat.label} className="bg-card p-5"><p className="text-sm text-muted-foreground">{stat.label}</p><p className="mt-3 text-3xl font-semibold tracking-tight">{stat.value}</p><p className="mt-2 text-xs text-muted-foreground">{stat.hint}</p></article>)}</div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(19rem,1fr)]"><article className="rounded-xl border bg-card p-5 md:p-6"><div className="flex items-start justify-between"><div><p className="font-semibold">{financial ? t("revenueEvolution") : t("dailyVolume")}</p><p className="mt-1 text-sm text-muted-foreground">{financial ? t("chartDescription") : t("dailyVolumeDescription")}</p></div><ArrowUpRight className="size-5 text-muted-foreground" /></div><RevenueChart series={metrics.series} locale={locale} currency={currency} /><div className="mt-5 flex gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-primary" />{financial ? t("received") : t("appointments")}</span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-muted-foreground/50" />{financial ? t("planned") : t("completed")}</span></div></article>
      <article className="rounded-xl border bg-card p-5 md:p-6"><div className="flex items-start justify-between"><div><p className="font-semibold">{t("teamPerformance")}</p><p className="mt-1 text-sm text-muted-foreground">{t("teamPerformanceDescription")}</p></div><Users className="size-5 text-muted-foreground" /></div><ol className="mt-6 space-y-4">{metrics.topStaff.length ? metrics.topStaff.map((member, index) => <li key={member.name} className="flex items-center gap-3"><span className="flex size-7 items-center justify-center rounded-full bg-muted text-xs font-semibold text-muted-foreground">{index + 1}</span><span className="min-w-0 flex-1 truncate text-sm font-medium">{member.name}</span><span className="text-right text-xs text-muted-foreground"><b className="block text-sm text-foreground">{member.completed}</b>{t("completedShort")}</span></li>) : <li className="py-8 text-center text-sm text-muted-foreground">{t("noData")}</li>}</ol></article></div>
    <div className="grid gap-6 lg:grid-cols-2"><article className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2"><CircleAlert className="size-5 text-amber-600" /><h2 className="font-semibold">{t("attention")}</h2></div>{metrics.pendingPayments.length ? <ul className="mt-4 divide-y">{metrics.pendingPayments.slice(0, 4).map((booking) => <li className="flex items-center justify-between gap-3 py-3" key={booking.id}><span><b className="block text-sm">{booking.customer}</b><span className="text-xs text-muted-foreground">{booking.service}</span></span><Link href="/dashboard/agenda" className="text-sm font-medium text-primary hover:underline">{t("openAgenda")}</Link></li>)}</ul> : <p className="mt-4 text-sm text-muted-foreground">{t("allClear")}</p>}</article><article className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2"><CircleCheck className="size-5 text-primary" /><h2 className="font-semibold">{t("nextStep")}</h2></div><p className="mt-4 text-sm leading-6 text-muted-foreground">{metrics.noShowCount ? t("noShowPrompt") : t("healthyPrompt")}</p><Link href="/dashboard/agenda" className="mt-5 inline-flex items-center gap-2 text-sm font-medium text-primary hover:underline"><CalendarDays className="size-4" />{t("viewAgenda")}</Link></article></div>
  </section>;
}
